import fs from 'node:fs';import path from 'node:path';import {createHash} from 'node:crypto';import {execFileSync} from 'node:child_process';
const out="/Users/pc/Documents/口播/edit/20260910_lanzhou_industry_ai/03_导演拆解/paper-v9.1-r4/first-frame-final-preparation-r1",root="/Users/pc/Documents/口播/edit/20260910_lanzhou_industry_ai/03_导演拆解/paper-v9.1-r4",read=p=>JSON.parse(fs.readFileSync(p)),sha=p=>createHash('sha256').update(fs.readFileSync(p)).digest('hex'),write=(p,v)=>fs.writeFileSync(p,JSON.stringify(v,null,2)+'\n',{flag:'wx'});
const jp=path.join(out,'first-frame-batch.v1.json'),j=read(jp),W=1672,H=941,box=([x,y,w,h])=>[x/W,y/H,w/W,h/H],quad=([x,y,w,h])=>[[x/W,y/H],[(x+w)/W,y/H],[(x+w)/W,(y+h)/H],[x/W,(y+h)/H]];
const cfg={
P05:{image:path.join(out,'local-structure-revision-r2/first-frames/P05_B15_first-frame.png'),sha:'3ed67f8def05e36517765c88787318d685ce01f088de74b60313326d8f0b8f1f',labels:[[79,186,431,99],[624,186,431,99],[1160,185,433,99]],inventory:[['reserve','G1',[334,410,151,49],'罩右侧只有一叠刚性成本纸垫。'],['work','G2',[697,471,125,112],'中央一份待水平展开的无字折页。']],stations:[['G1',['reserve'],[73,185,441,459],'同台罩体和纸垫；纸垫由右向左。'],['G2',['work'],[623,185,613,454],'中央待展开工作件；宽平台面延续至右区。'],['G3',[],[1159,185,443,454],'右蓝色接收槽初态空，左口开放。']],transfers:[['A3',[697,496,817,114],'实际全图可见暖白台面和蓝接收底面连续，前沿同线，左口无端墙；支撑宽于折页展开运输路径。']],notes:'三张独立空白固定牌；罩与成本纸垫共用台面，入口朝右，纸垫在口外，向左可被较长不透明罩遮蔽。中央仅一份待展开折页，右侧接收位空。原高挡墙已不存在；暖白/蓝底前沿同线。纸纤维、纸厚、台前沿和牌架呈现多层，主体完整留在安全区，字幕区空。源导演已独立实际复核此哈希的可见结构，未发现明确硬阻断。内部空间和毫米净空不可从单图证明，动态另验。'},
P06:{image:path.join(out,'local-structure-polish-P06-r4/P06_B17_first-frame.png'),sha:'37c98abe71b70e5223cee8684ab7b5ed23e2cca8f61e10a56f35667a5a59ab6e',labels:[[116,155,309,92],[495,154,307,92],[872,154,305,92],[1250,153,304,91]],inventory:[['scope','G1',[181,422,153,34],'左上源托盘仅一张空白工作范围纸卡。'],['cooperation','G2',[618,550,131,35],'中下源托盘仅一张空白配合纸卡。']],stations:[['G1',['scope'],[115,153,311,350],'第一固定牌与上路左端源托盘，右端开放。'],['G2',['cooperation'],[494,153,310,502],'第二固定牌与下路左端源托盘，右端开放。'],['G3',[],[871,153,308,485],'共同打开的文件夹背板与两个空接收托面，夹子静止。'],['G4',[],[1249,152,310,506],'第四牌和独立放大镜查问题桌；不作成功确认。']],transfers:[['A1',[181,410,907,69],'上路起点纸卡与长托面直接相连，右口无墙，接收区左向开放，预定终点在右端挡翼之前。'],['A2',[618,538,470,72],'下路为独立整张连续托面，源托盘右口开放，同路无台阶，空接收区与桥面同高。']],notes:'实际全图检查：四张空白固定牌及独立支脚；两张唯一活动卡分别位于左上和中下源托盘，两个右侧接收位置均空。通道为连续纸面，文件夹背板、纸夹和G4放大镜可辨。已去除上一候选的矩形硬边、旧机构重影和悬空亮线；纸材纤维、边厚、托面阴影与后景牌架保持可辨，多层空间，全部实体在安全区，底部字幕区空。局部合成的托面质感比原生G4略平整，留待用户审美确认；不把像素上下位置解释为毫米高度。'}};
j.output.imageRoot=out;
for(const[id,c]of Object.entries(cfg)){if(sha(c.image)!==c.sha)throw Error('图片变化：'+id);const sc=j.scenes.find(s=>s.sceneId===id);sc.outputPath=c.image;
const physical={imageSha256:c.sha,physicalContractSha256:sc.physicalContractSha256,inventory:c.inventory.map(([partId,g,b,notes])=>({partId,observedQuantity:1,observedGroupIds:[g],imageBoxes:[box(b)],notes})),stations:c.stations.map(([groupId,observedPartIds,b,notes])=>({groupId,observedPartIds,imageBox:box(b),notes})),transfers:c.transfers.map(([actionId,b,notes])=>({actionId,imageBox:box(b),checks:{continuousSupport:'passed',compatibleHeight:'passed',noBlockingEdges:'passed',openingFitsPart:'passed'},notes})),fixedLabels:c.labels.map((b,i)=>({nodeId:'N'+(i+1),imageBox:box(b),independentStandObserved:true,notes:'实际牌面与两根静态支脚可辨，活动通道在下方，不与运动部件相连。'}))};
if(id==='P05')physical.sameGroupActionObservations=[{actionId:'A1',numericValidatorCoverage:false,visibleSupport:'同一蓝色台顶面，无下落与转弯',entryDirection:'纸垫在罩右、由右向左',opaqueCoverLongerThanVisiblePad:true,hiddenInteriorMeasured:false,notes:'罩的画面覆盖长度略大于纸垫；只判可见结构，没有实际毫米量测。'}];
write(path.join(j.output.qaRoot,id+'.visual-review.v1.json'),{schemaVersion:'koubo-paper-firstframe-visual-review/v1',sceneId:id,imagePath:c.image,imageSha256:c.sha,reviewer:'codex-actual-full-image-review',reviewedAt:new Date().toISOString(),status:'passed',criteria:Object.fromEntries(['semanticMatch','paperMaterial','depthAndContact','cleanTextAndBrand','compositionAndReadability','videoReadiness'].map(k=>[k,'passed'])),notes:c.notes,physicalObservations:physical,actualMillimetreClearanceVerified:false,dynamicAccepted:false,userAcceptance:'pending'});
write(sc.deterministicTextBake.calibrationPath,{schemaVersion:'koubo-paper-firstframe-anchor-calibration/v1',sceneId:id,status:'passed',sourceImage:{path:c.image,sha256:c.sha},calibrationBasis:'本轮实际打开最终无字图后标定，非计划坐标',labels:c.labels.map((b,i)=>({nodeId:'N'+(i+1),anchorQuad:quad(b),placementChecked:true}))});}
fs.writeFileSync(jp,JSON.stringify(j,null,2)+'\n');
for(const[id,c]of Object.entries(cfg)){execFileSync(process.execPath,['skills/koubo-paper-firstframe-producer/scripts/record-firstframe-result.mjs','--job',jp,'--scene',id,'--image',c.image,'--execution-prompt-file',path.join(j.output.qaRoot,id+'.execution-prompt.txt'),'--tool','image_gen+local-deterministic-structure-composite'],{stdio:'inherit'});}
write(path.join(out,'canvas-preparation-authorization.v1.json'),{schemaVersion:'koubo-canvas-preparation-authorization/v1',status:'authorized-for-canvas-preparation',taskId:j.taskId,requestId:j.requestId,revisionId:j.revisionId,sourceManifest:j.sourceManifest,sceneIds:j.scenes.map(s=>s.sceneId),userQuote:'那在不用问我啊，按照现有修复的导演思维skill，直接将所有的图片首帧生成完毕之后放入running好，等待视频生成就行',recordedAt:new Date().toISOString(),uploadAllowed:true,canvasConfigurationAllowed:true,submissionAllowed:false,paidGenerationAllowed:false,userAcceptance:'pending'});
