import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {fileURLToPath} from 'node:url';
const out=path.dirname(fileURLToPath(import.meta.url));
const m=JSON.parse(fs.readFileSync(path.join(out,'machine-intake.v1.json')));
const hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const notes={
 F1:{slot:'P03',meaning:'四种人的驾驶职责；方向盘、道路判断窗、驾驶员、分岔决策杆对应四牌。',actions:['约0–1.5秒：左方向盘角度变化','约1.5–3秒：道路窗遮片切换','约3.5–5秒：驾驶员伸手拨动右侧决策杆','约5.5秒后：手臂收回，末段主要定格'],geometry:'左侧独立方向盘与驾驶员手中方向盘重复，继承参考首帧的已知问题；伸臂动作看得出关节变化，未据抽帧发现确定性崩坏，但未连续检验手部。',recommendation:{in:0,outExclusive:7},concerns:['重复方向盘须父任务确认表达是否可接受','6.083秒后检测到多段近静止，不能称全程持续动作']},
 F2:{slot:'P04',meaning:'上层软件向商业工作交付纸片，下层门/汽车独立运动，空间隔板保持，无跨层控制线。',actions:['约0–2秒：软件端文件翻出，红纸沿上层轨道进入商业工作托盘','约2.5–4秒：下层门开合','约4–6秒：汽车由右侧向左侧移动并压到红片附近','约6.5秒后：收束近静止'],geometry:'上下层、托盘和车辆身份保持；汽车离开执行身体牌位是运动结果，不是牌面错配证据。未见确定性文字变形。',recommendation:{in:0,outExclusive:7},concerns:['只表达软件与现实执行对照，不推导已经完全打通或全自主','2.333–2.875秒及尾部检测近静止']},
 F3:{slot:'P06',meaning:'营销资料、视觉色样、SOP折页、数据册分别变化，四类服务对象对应清楚，不显示结果承诺。',actions:['约0–1秒：左侧资料纸竖起/进入资料夹','约0.5–2秒：SOP折页展开，视觉色样落到画架前','约2–4秒：四组物件收束，数据册翻动开始','约4.5–6秒：右侧数据册翻页并回落'],geometry:'纸张折叠、展开和翻页属于设计动作；抽帧未见明确文字错字或失去对象身份。运动过渡的穿插/闪烁未原速验收。',recommendation:{in:0,outExclusive:6},concerns:['6秒槽位截取建议为0–6秒，联系表6秒附近已有四组物件；精确动作收尾仍需原速复核','全片比槽位多1.291667秒，不代表都能无损删除']},
 F4:{slot:'P02',meaning:'业务任务红纸移到电脑；资料从中间整理槽经过排查框，到右侧交付盒。',actions:['约0–1.5秒：电脑打开，红任务纸落到电脑台面','约2–3.5秒：中间资料纸弹起并汇聚','约3.5–5.5秒：资料堆经过排查框','约6–7秒：资料堆移入交付结果盒，末帧已装入'],geometry:'电脑由闭到开与纸张由散到叠是动作变化；牌面与五站布局对应参考首帧。未发现确定错字；检查框在资料前后关系需连续复核。',recommendation:null,concerns:['原片7.291667秒小于8秒槽位，缺0.708333秒；原速不能填满，不许冻结补齐','交付动作接近末尾，不能随意裁掉末段；父任务需缩短纸艺覆盖或重排已有覆盖，本子任务不改时间轴']},
 F5:{slot:'P05',meaning:'前景决策杆、判断样板、服务座椅、经营册依次变化；人物保留。',actions:['约0–1.5秒：决策杆与判断样板变化','约1.5–3秒：服务座椅旋转、经营册翻开','约3–4.5秒：座椅与书页回落','约5秒后：前景动作基本结束，尾部近静止'],geometry:'末帧四牌均可读；人物与物件身份保持。背景重复任务轨道的连续运行未从这些抽帧建立，不能宣称该机制已完整展示。',recommendation:{in:0,outExclusive:7},concerns:['5.167–7.292秒几乎连续近静止，7秒采用窗口内约1.833秒属于近静止尾段','源声5.416秒起静音至片尾，可能是收束设计，不等于损坏','背景重复任务动态证据不足，应作表达风险交父任务']},
 F6:{slot:'P01',meaning:'左侧一问一答物件与右侧电脑、浏览器、业务软件对照；纸片经浏览器区域进入抽屉。',actions:['约0–1.5秒：左侧对话物件位移','约2–3秒：浏览器面板翻动，红纸向右移','约3–4.5秒：红纸进入业务软件抽屉','约5秒后：以定姿/小变化收尾'],geometry:'任务红纸起点已在电脑与浏览器之间，继承参考首帧问题，不能称从空白入口开始完整装配；文字牌面在抽查帧可读，未見明确崩坏。',recommendation:{in:0,outExclusive:7},concerns:['源声真峰值约+0.1 dB，需听审并保留混音余量，不能直接加增益','纸片起点位置与完整流程预期存在偏差；5秒后含近静止段']}
};
const issues={P0:[{id:'P0-01',slots:['P02'],finding:'视频_4.mp4仅7.291667秒，当前P02槽位8秒；在原速且禁止冻结延长的约束下无法填满。',action:'阻断直接按原8秒槽位接入。父任务裁决缩短覆盖/重排既有覆盖；本子任务不改时间轴。'}],P1:[{id:'P1-01',slots:['P01'],finding:'源音轨真峰值约+0.1 dB；未进行原速听审，不能证明无爆音。',action:'保留原声文件，混音前听审，避免直接加增益。'},{id:'P1-02',slots:['P05'],finding:'末段约5.167秒起近静止，5.416秒后静音；背景重复任务轨道动态未从抽帧建立。',action:'父任务确认动作意义与尾部节奏，不能用机器无黑场替代动态验收。'},{id:'P1-03',slots:['P03'],finding:'画面有独立方向盘及驾驶员手中方向盘两套道具，参考首帧已记录该问题。',action:'确认是否接受，不能登记为没有既有视觉问题。'},{id:'P1-04',slots:['P01','P02','P03','P04','P05','P06'],finding:'本次只有完整解码、信号检测和静帧序列查看，没有原速完整听看，未确认逐动作音效、瞬时变形与字幕合成后避让。',action:'状态维持机器检查与映射完成、动态听看待验；不得正式验收。'}],P2:[{id:'P2-01',slots:['P01','P02','P03','P04','P05','P06'],finding:'Tesseract末帧OCR大量漏识；目视六组节点字均可读，未发现确定错字。',action:'保留原OCR，不把漏识转成错字工单。'},{id:'P2-02',slots:['P01','P03','P04','P06'],finding:'检测到至少0.5秒近静止区间，可能是有意留白，不等同复制帧故障。',action:'按动作和讲解判断保留，禁止额外冻结延长。'},{id:'P2-03',slots:['P01'],finding:'红色任务片首帧已位于电脑/浏览器之间，未严格从入口开始。',action:'沿用参考首帧边界，不夸称完整装配起点。'},{id:'P2-04',slots:['P01','P02','P03','P04','P05','P06'],finding:'24fps源片接30fps工程需正常时间采样；源声响度跨度约10 LU，未按听感统一。',action:'父任务保持时长与画幅，勿以改帧率误改速度。'}]};
const assets=m.assets.map(a=>{
 const n=notes[a.fileId],slot=m.slots.find(s=>s.id===n.slot),ref=m.references.find(r=>r.id===n.slot);
 const metric=(re)=>{const x=a.loudnessSummary?.match(re);return x?Number(x[1]):null;};
 const freeze=[];let current=null;
 for(const line of a.signalEvents){let x;if((x=line.match(/freeze_start: ([\d.]+)/)))current=Number(x[1]);if((x=line.match(/freeze_end: ([\d.]+)/))&&current!==null){freeze.push({start:current,end:Number(x[1]),endInferredFromEof:false});current=null;}}
 if(current!==null)freeze.push({start:current,end:a.durationSeconds,endInferredFromEof:true});
 const unchanged=hash(a.path)===a.sha256;
 return {...a,mappedSlot:n.slot,mappingBasis:'六组画面物件、牌面语义及参考首帧对应；不是文件名顺序',mappingConfidence:'高',reference:ref,referenceShaUnchanged:hash(ref.path)===ref.sha256,sourceShaUnchanged:unchanged,labelsExpected:slot.labels,labelsVisualCheck:{status:'末帧目视可读，未发现确定错字',observed:slot.labels,scope:'已查看每半秒联系表与7.250秒末帧；非每帧OCR通过'},visualReview:{meaning:n.meaning,actionBoundaries:n.actions,boundaryPrecision:'约0.5秒级抽帧观察，非精确切点',deformation:n.geometry,concerns:n.concerns},durationFit:{slotSeconds:slot.requestedDurationSeconds,marginSeconds:a.durationSeconds-slot.requestedDurationSeconds,sourceFrameCount:175,sourceFps:24,recommendedSourceRange:n.recommendation,speed:1,freezeExtensionAllowed:false},signalAnalysis:{blackIntervalsDetected:a.signalEvents.filter(s=>s.includes('black_start')),nearStillIntervals:freeze,interpretation:'-50dB、至少0.5秒近静止检测；不等于像素完全相同或异常卡死',integratedLufs:metric(/I:\s+(-?[\d.]+) LUFS/),loudnessRangeLu:metric(/LRA:\s+(-?[\d.]+) LU/),truePeakDb:metric(/Peak:\s+(-?[\d.]+) dBFS/)},audioReview:{hasSourceAudio:a.audio.length>0,listened:false,contentType:'未听审，不能确定是配乐、动作音效、语音或混合',perActionSoundSyncAccepted:false,mixingGainChosen:false},status:n.slot==='P02'?'blocked-duration-fit':'mapped-machine-checked-human-playback-pending'};
}).sort((a,b)=>a.mappedSlot.localeCompare(b.mappedSlot));
const result={schemaVersion:'paper-asset-intake/v1',createdAt:new Date().toISOString(),status:'六镜映射与机器检查完成；P02时长接入阻断，全部待原速听看',formalEnabled:false,finalAccepted:false,fullSpeedWatched:false,audioListened:false,planPath:m.planPath,planSha256:m.planSha256,planUnchanged:hash(m.planPath)===m.planSha256,machineReport:'machine-intake.v1.json',visualEvidence:'六张0.5秒间隔联系表共90格及六张7.250秒末帧已实际查看；参考首帧总览已查看',priorityDefinitions:{P0:'阻断当前计划直接接入',P1:'使用前需处理或明确接受',P2:'提醒及待连续复核'},issues,assets};
fs.writeFileSync(path.join(out,'asset-intake.v1.json'),JSON.stringify(result,null,2)+'\n',{flag:'wx'});
const lines=['# 六段纸艺接收 r1','','## 机器结果与映射','','六段均为2560×1440、24fps、175帧、7.291667秒，均有音轨，完整解码退出码0。未检测到满足本次阈值的黑场；不等于无局部黑块、无瞬闪或动态已验收。','','|槽位|源文件|槽位秒数|源片余量秒|综合响度LUFS|真峰值dB|联系表|','|---|---|---:|---:|---:|---:|---|'];
for(const a of assets)lines.push(`|${a.mappedSlot}|${a.file}|${a.durationFit.slotSeconds}|${a.durationFit.marginSeconds.toFixed(6)}|${a.signalAnalysis.integratedLufs}|${a.signalAnalysis.truePeakDb}|[${a.fileId}](${a.contactSheet})|`);
lines.push('','## P0 / P1 / P2','');
for(const [level,items]of Object.entries(issues))for(const i of items)lines.push(`- **${level} ${i.id} ${i.slots.join('、')}**：${i.finding} ${i.action}`);
lines.push('','## 已查看的联系表','','每张从左到右、从上到下，约0、0.5、1.0……7.0秒。采样经fps滤镜重采样，动作时点精度只到约0.5秒，不冒充精确源帧PTS。单独末帧为7.250秒。');
for(const a of assets){lines.push('',`### ${a.mappedSlot}：${a.file}`,`![${a.mappedSlot}半秒联系表](${a.contactSheet})`,`![${a.mappedSlot}末帧](${a.frames.at(-1).file})`,'',a.visualReview.meaning,...a.visualReview.actionBoundaries.map(s=>'- '+s),'',a.visualReview.deformation,`近静止区间：${a.signalAnalysis.nearStillIntervals.map(x=>`${x.start.toFixed(3)}–${x.end.toFixed(3)}秒${x.endInferredFromEof?'（至片尾推定）':''}`).join('；')||'未检出'}。`,...a.visualReview.concerns.map(s=>'- '+s));}
lines.push('','## 验收边界','','末帧六组文字目视均可读，未发现确定错字；Tesseract已运行，但文字较小、纸纹与透视造成漏识。OCR结果原样保存，不自动修字。','完整解码、静音检测和响度统计不等于原速听审。没有确定源音轨内容类型，没有确认动作音效同步，没有决定混音增益。真峰值轻微超0仅是风险信号，不等于已听到爆音。','未原速完整播放，未验收瞬时形变/闪烁，也未验收合成后字幕和纸面文字是否遮挡。全部保持未最终验收；没有新生成视频、登录、外网、付费、字幕修改、共享组件修改或Git提交。','冻结检测指阈值内近静止，正常纸艺收尾也会命中；不是新增冻结补时。P02严禁靠末帧冻结填到8秒。','两次SHA绑定核验范围为本轮六份源视频、六张参考首帧及v2对位JSON，状态见JSON；不宣称仓库其他协作者没有改动。');
fs.writeFileSync(path.join(out,'接收复核与联系表.v1.md'),lines.join('\n')+'\n',{flag:'wx'});
if(assets.some(a=>!a.sourceShaUnchanged||!a.referenceShaUnchanged)||!result.planUnchanged)throw Error('输入发生变化，需父任务复核');
console.log(JSON.stringify({mapped:assets.map(a=>({slot:a.mappedSlot,file:a.file,margin:a.durationFit.marginSeconds})),fullDecodeAllPassed:assets.every(a=>a.fullDecodeExitCode===0),inputHashesUnchanged:true,P0:issues.P0.length,P1:issues.P1.length,P2:issues.P2.length,createdAt:result.createdAt}));
