import React from 'react';
import {Composition, Folder, Still} from 'remotion';
import {
  AILandingFieldDocumentaryV2,
  AI_LANDING_DOCUMENTARY_V2_DURATION_IN_FRAMES,
} from './AILandingFieldDocumentaryV2';
import {AILandingFieldTalk16x9, AI_LANDING_DURATION_IN_FRAMES} from './AILandingFieldTalk16x9';
import {AIBizTalk16x9} from './AIBizTalk16x9';
import {AIStoreAssetPreview16x9} from './AIStoreAssetPreview16x9';
import {AIStoreTalk16x9} from './AIStoreTalk16x9';
import {CoverStill} from './CoverStill';
import {CoverStill3x4} from './CoverStill3x4';
import {CoverStill9x16} from './CoverStill9x16';
import {DigitalOneTalk16x9} from './DigitalOneTalk16x9';
import {TokenV5AssetPreview16x9} from './TokenV5AssetPreview16x9';
import {TokenV5Talk16x9} from './TokenV5Talk16x9';
import {
  WAICV6Preview16x9,
  WAICV6Talk16x9,
  WAIC_V6_DURATION_IN_FRAMES,
  WAIC_V6_PREVIEW_DURATION_IN_FRAMES,
} from './WAICV6Talk16x9';
import {
  WAICV7TransparentTest16x9,
  WAIC_V7_TEST_DURATION_IN_FRAMES,
} from './WAICV7TransparentTest16x9';
import {
  DazhiFormalV7Talk16x9,
  DAZHI_FORMAL_DURATION_IN_FRAMES,
} from './DazhiFormalV7Talk16x9';
import {
  TwoLedgersV7Talk16x9,
  TwoLedgersV7Talk16x9NoSfx,
  TWO_LEDGER_DURATION_IN_FRAMES,
} from './TwoLedgersV7Talk16x9';
import {
  HokkaidoV71StylePreview16x9,
  HokkaidoV71StylePreview16x9NoSfx,
  HOKKAIDO_V71_PREVIEW_DURATION_IN_FRAMES,
} from './HokkaidoV71StylePreview16x9';
import {
  HokkaidoThreeProjectsAssetPreflight16x9,
  HOKKAIDO_THREE_PROJECTS_PREFLIGHT_DURATION_IN_FRAMES,
} from './HokkaidoThreeProjectsAssetPreflight16x9';
import {
  HokkaidoThreeProjectsTalk16x9,
  HokkaidoThreeProjectsTalk16x9V72NoSfx,
  HokkaidoThreeProjectsTalk16x9V72WithSfx,
  HokkaidoThreeProjectsTalk16x9WithSfx,
  HOKKAIDO_THREE_PROJECTS_DURATION_IN_FRAMES,
} from './HokkaidoThreeProjectsTalk16x9';
import {
  RuishengGeoField16x9,
  RuishengGeoField16x9V2,
  RUISHENG_GEO_DURATION_IN_FRAMES,
  RUISHENG_GEO_V2_DURATION_IN_FRAMES,
} from './RuishengGeoField16x9';
import {
  defaultTalkProps,
  gansuStoreAiTalk01Props,
  geoAiRecommendTalk01Props,
  localBusinessAiDailyTalk01Props,
  localBossAiOcrDemoProps,
  localBossAiProps,
  localBossAiV2Props,
  opcWestYouthTalk01Props,
  smallBusinessAiV1Props,
} from './data/story';

export const RemotionRoot: React.FC = () => {
  return (
    <>
      <Folder name="Koubo">
        <Composition
          id="HokkaidoThreeProjectsTalk16x9-NoSfx"
          component={HokkaidoThreeProjectsTalk16x9}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={HOKKAIDO_THREE_PROJECTS_DURATION_IN_FRAMES}
        />
        <Composition
          id="HokkaidoThreeProjectsTalk16x9-WithSfx"
          component={HokkaidoThreeProjectsTalk16x9WithSfx}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={HOKKAIDO_THREE_PROJECTS_DURATION_IN_FRAMES}
        />
        <Composition
          id="HokkaidoThreeProjectsTalk16x9-V72-NoSfx"
          component={HokkaidoThreeProjectsTalk16x9V72NoSfx}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={HOKKAIDO_THREE_PROJECTS_DURATION_IN_FRAMES}
        />
        <Composition
          id="HokkaidoThreeProjectsTalk16x9-V72-WithSfx"
          component={HokkaidoThreeProjectsTalk16x9V72WithSfx}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={HOKKAIDO_THREE_PROJECTS_DURATION_IN_FRAMES}
        />
        <Composition
          id="HokkaidoThreeProjectsAssetPreflight16x9"
          component={HokkaidoThreeProjectsAssetPreflight16x9}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={HOKKAIDO_THREE_PROJECTS_PREFLIGHT_DURATION_IN_FRAMES}
        />
        <Composition
          id="HokkaidoV71StylePreview16x9-WithSfx"
          component={HokkaidoV71StylePreview16x9}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={HOKKAIDO_V71_PREVIEW_DURATION_IN_FRAMES}
        />
        <Composition
          id="HokkaidoV71StylePreview16x9-NoSfx"
          component={HokkaidoV71StylePreview16x9NoSfx}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={HOKKAIDO_V71_PREVIEW_DURATION_IN_FRAMES}
        />
        <Composition
          id="TwoLedgersV7Talk16x9-WithSfx"
          component={TwoLedgersV7Talk16x9}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={TWO_LEDGER_DURATION_IN_FRAMES}
        />
        <Composition
          id="TwoLedgersV7Talk16x9-NoSfx"
          component={TwoLedgersV7Talk16x9NoSfx}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={TWO_LEDGER_DURATION_IN_FRAMES}
        />
        <Composition
          id="DazhiFormalV7Talk16x9"
          component={DazhiFormalV7Talk16x9}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={DAZHI_FORMAL_DURATION_IN_FRAMES}
        />
        <Composition
          id="WAICV7TransparentTest16x9"
          component={WAICV7TransparentTest16x9}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={WAIC_V7_TEST_DURATION_IN_FRAMES}
        />
        <Composition
          id="WAICV6Talk16x9-Final"
          component={WAICV6Talk16x9}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={WAIC_V6_DURATION_IN_FRAMES}
        />
        <Composition
          id="WAICV6Talk16x9-Preview"
          component={WAICV6Preview16x9}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={WAIC_V6_PREVIEW_DURATION_IN_FRAMES}
        />
        <Composition
          id="RuishengGeoField16x9-V2"
          component={RuishengGeoField16x9V2}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={RUISHENG_GEO_V2_DURATION_IN_FRAMES}
        />
        <Composition
          id="RuishengGeoField16x9-Final"
          component={RuishengGeoField16x9}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={RUISHENG_GEO_DURATION_IN_FRAMES}
        />
        <Composition
          id="AILandingFieldDocumentaryV2-Rough"
          component={AILandingFieldDocumentaryV2}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={AI_LANDING_DOCUMENTARY_V2_DURATION_IN_FRAMES}
        />
        <Composition
          id="AILandingFieldTalk16x9-Final"
          component={AILandingFieldTalk16x9}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={AI_LANDING_DURATION_IN_FRAMES}
        />
        <Composition
          id="TokenV5Talk16x9-Final"
          component={TokenV5Talk16x9}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={6595}
        />
        <Composition
          id="TokenV5AssetPreview16x9"
          component={TokenV5AssetPreview16x9}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={1680}
        />
        <Composition
          id="Digital1Talk16x9-Final"
          component={DigitalOneTalk16x9}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={5247}
        />
        <Composition
          id="AIStoreTalk16x9-Final"
          component={AIStoreTalk16x9}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={7462}
        />
        <Composition
          id="AIStoreAssetPreview16x9"
          component={AIStoreAssetPreview16x9}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={960}
        />
        <Composition
          id="AIBizTalk16x9"
          component={AIBizTalk16x9}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={2380}
          defaultProps={defaultTalkProps}
        />
        <Composition
          id="AIBizTalk16x9-IMG1926"
          component={AIBizTalk16x9}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={1848}
          defaultProps={localBossAiProps}
        />
        <Composition
          id="AIBizTalk16x9-IMG1926-v2"
          component={AIBizTalk16x9}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={1848}
          defaultProps={localBossAiV2Props}
        />
        <Composition
          id="AIBizTalk16x9-OCRDemo"
          component={AIBizTalk16x9}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={120}
          defaultProps={localBossAiOcrDemoProps}
        />
        <Composition
          id="AIBizTalk16x9-SmallBusinessAI-v1"
          component={AIBizTalk16x9}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={5082}
          defaultProps={smallBusinessAiV1Props}
        />
        <Composition
          id="AIBizTalk16x9-GansuStoreAI-Talk01"
          component={AIBizTalk16x9}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={3543}
          defaultProps={gansuStoreAiTalk01Props}
        />
        <Composition
          id="AIBizTalk16x9-GEO-AIRecommend-Talk01"
          component={AIBizTalk16x9}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={7306}
          defaultProps={geoAiRecommendTalk01Props}
        />
        <Composition
          id="AIBizTalk16x9-LocalBusinessAI-Daily-Talk01"
          component={AIBizTalk16x9}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={4405}
          defaultProps={localBusinessAiDailyTalk01Props}
        />
        <Composition
          id="AIBizTalk16x9-OPC-WestYouth-Talk01"
          component={AIBizTalk16x9}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={5670}
          defaultProps={opcWestYouthTalk01Props}
        />
        <Still
          id="CoverStill"
          component={CoverStill}
          width={1920}
          height={1080}
          defaultProps={defaultTalkProps}
        />
        <Still
          id="CoverStill3x4"
          component={CoverStill3x4}
          width={1080}
          height={1440}
          defaultProps={defaultTalkProps}
        />
        <Still
          id="CoverStill3x4-IMG1926"
          component={CoverStill3x4}
          width={1080}
          height={1440}
          defaultProps={localBossAiProps}
        />
        <Still
          id="CoverStill3x4-IMG1926-v2"
          component={CoverStill3x4}
          width={1080}
          height={1440}
          defaultProps={localBossAiV2Props}
        />
        <Still
          id="CoverStill9x16"
          component={CoverStill9x16}
          width={1080}
          height={1920}
          defaultProps={defaultTalkProps}
        />
      </Folder>
    </>
  );
};
