import React from 'react';
import {Composition, Folder, Still} from 'remotion';
import {
  AILandingFieldDocumentaryV2,
  AI_LANDING_DOCUMENTARY_V2_DURATION_IN_FRAMES,
} from './AILandingFieldDocumentaryV2';
import {AILandingFieldTalk16x9, AI_LANDING_DURATION_IN_FRAMES} from './AILandingFieldTalk16x9';
import {AIBizTalk16x9} from './AIBizTalk16x9';
import {AIStoreAssetPreview16x9} from './AIStoreAssetPreview16x9';
import {AIStoreTalk16x9} from './AIStoreTalk16x9';
import {CoverStill} from './CoverStill';
import {CoverStill3x4} from './CoverStill3x4';
import {CoverStill9x16} from './CoverStill9x16';
import {DigitalOneTalk16x9} from './DigitalOneTalk16x9';
import {TokenV5AssetPreview16x9} from './TokenV5AssetPreview16x9';
import {TokenV5Talk16x9} from './TokenV5Talk16x9';
import {
  WAICV6Preview16x9,
  WAICV6Talk16x9,
  WAIC_V6_DURATION_IN_FRAMES,
  WAIC_V6_PREVIEW_DURATION_IN_FRAMES,
} from './WAICV6Talk16x9';
import {
  WAICV7TransparentTest16x9,
  WAIC_V7_TEST_DURATION_IN_FRAMES,
} from './WAICV7TransparentTest16x9';
import {
  DazhiFormalV7Talk16x9,
  DAZHI_FORMAL_DURATION_IN_FRAMES,
} from './DazhiFormalV7Talk16x9';
import {
  TwoLedgersV7Talk16x9,
  TwoLedgersV7Talk16x9NoSfx,
  TWO_LEDGER_DURATION_IN_FRAMES,
} from './TwoLedgersV7Talk16x9';
import {
  HokkaidoV71StylePreview16x9,
  HokkaidoV71StylePreview16x9NoSfx,
  HOKKAIDO_V71_PREVIEW_DURATION_IN_FRAMES,
} from './HokkaidoV71StylePreview16x9';
import {
  HokkaidoThreeProjectsAssetPreflight16x9,
  HOKKAIDO_THREE_PROJECTS_PREFLIGHT_DURATION_IN_FRAMES,
} from './HokkaidoThreeProjectsAssetPreflight16x9';
import {
  HokkaidoThreeProjectsTalk16x9,
  HokkaidoThreeProjectsTalk16x9V72NoSfx,
  HokkaidoThreeProjectsTalk16x9V72WithSfx,
  HokkaidoThreeProjectsTalk16x9WithSfx,
  HOKKAIDO_THREE_PROJECTS_DURATION_IN_FRAMES,
} from './HokkaidoThreeProjectsTalk16x9';
import {
  ChildAIInterviewV72NoSfx,
  ChildAIInterviewV72WithSfx,
  CHILD_AI_INTERVIEW_DURATION_IN_FRAMES,
} from './ChildAIInterviewV72';
import {
  CycleAssetsV72Talk16x9NoSfx,
  CycleAssetsV72Talk16x9WithSfx,
  CYCLE_ASSETS_DURATION_IN_FRAMES,
} from './CycleAssetsV72Talk16x9';
import {
  V72DataDrivenPreview16x9NoSfx,
  V72DataDrivenPreview16x9WithSfx,
  V72_DATA_DRIVEN_PREVIEW_DURATION_IN_FRAMES,
} from './V72DataDrivenPreview16x9';
import {
  TrustOpcScenarioAsset16x9,
  TrustAssetPreflight16x9,
  TrustStoreScenarioAsset16x9,
  TrustThreeGatesAsset16x9,
  TrustTimelineAsset16x9,
  TRUST_ASSET_PREFLIGHT_DURATION_IN_FRAMES,
} from './TrustAssetPreflight16x9';
import {
  TrustV72Talk16x9NoSfx,
  TrustV72Talk16x9WithSfx,
  TRUST_V72_DURATION_IN_FRAMES,
} from './TrustV72Talk16x9';
import {
  LanzhouOpcV72Talk16x9NoSfx,
  LanzhouOpcV72Talk16x9WithSfx,
  LANZHOU_OPC_DURATION_IN_FRAMES,
} from './LanzhouOpcV72Talk16x9';
import {
  AIProductivityV73Talk16x9NoSfx,
  AIProductivityV73Talk16x9WithSfx,
  AI_PRODUCTIVITY_V73_DURATION_IN_FRAMES,
} from './AIProductivityV73Talk16x9';
import {
  AICognitivePositionV73Talk16x9NoSfx,
  AICognitivePositionV73Talk16x9WithSfx,
  AI_COGNITIVE_POSITION_V73_DURATION_IN_FRAMES,
} from './AICognitivePositionV73Talk16x9';
import {
  AICognitivePositionV80Talk16x9NoSfx,
  AICognitivePositionV80Talk16x9WithSfx,
  AI_COGNITIVE_POSITION_V80_DURATION_IN_FRAMES,
} from './AICognitivePositionV80Talk16x9';
import {
  AISelfMediaAssetPreflight16x9NoSfx,
  AISelfMediaAssetPreflight16x9WithSfx,
  AI_SELF_MEDIA_ASSET_PREFLIGHT_DURATION_IN_FRAMES,
} from './AISelfMediaAssetPreflight16x9';
import {
  AISelfMediaV73Talk16x9NoSfx,
  AISelfMediaV73Talk16x9WithSfx,
  AI_SELF_MEDIA_V73_DURATION_IN_FRAMES,
} from './AISelfMediaV73Talk16x9';
import {
  TrainingCampV80Talk16x9NoSfx,
  TrainingCampV80Talk16x9WithSfx,
  TRAINING_CAMP_V80_DURATION_IN_FRAMES,
} from './TrainingCampV80Talk16x9';
import {
  BestWorstV8PrimitivePreview16x9,
  BEST_WORST_V8_PRIMITIVE_PREVIEW_DURATION_IN_FRAMES,
} from './BestWorstV8PrimitivePreview16x9';
import {
  AIBestWorstV80Preview45s16x9NoSfx,
  AIBestWorstV80Preview45s16x9WithSfx,
  AI_BEST_WORST_V80_PREVIEW_DURATION_IN_FRAMES,
} from './AIBestWorstV80Preview45s16x9';
import {
  AIBestWorstV80Talk16x9NoSfx,
  AIBestWorstV80Talk16x9WithSfx,
  AI_BEST_WORST_V80_DURATION_IN_FRAMES,
} from './AIBestWorstV80Talk16x9';
import {
  RuishengGeoField16x9,
  RuishengGeoField16x9V2,
  RUISHENG_GEO_DURATION_IN_FRAMES,
  RUISHENG_GEO_V2_DURATION_IN_FRAMES,
} from './RuishengGeoField16x9';
import {
  defaultTalkProps,
  gansuStoreAiTalk01Props,
  geoAiRecommendTalk01Props,
  localBusinessAiDailyTalk01Props,
  localBossAiOcrDemoProps,
  localBossAiProps,
  localBossAiV2Props,
  opcWestYouthTalk01Props,
  smallBusinessAiV1Props,
} from './data/story';

export const RemotionRoot: React.FC = () => {
  return (
    <>
      <Folder name="Koubo">
        <Composition
          id="AIBestWorst16x9-V80-WithSfx"
          component={AIBestWorstV80Talk16x9WithSfx}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={AI_BEST_WORST_V80_DURATION_IN_FRAMES}
        />
        <Composition
          id="AIBestWorst16x9-V80-NoSfx"
          component={AIBestWorstV80Talk16x9NoSfx}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={AI_BEST_WORST_V80_DURATION_IN_FRAMES}
        />
        <Composition
          id="AIBestWorst16x9-V80-Preview45-WithSfx"
          component={AIBestWorstV80Preview45s16x9WithSfx}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={AI_BEST_WORST_V80_PREVIEW_DURATION_IN_FRAMES}
        />
        <Composition
          id="AIBestWorst16x9-V80-Preview45-NoSfx"
          component={AIBestWorstV80Preview45s16x9NoSfx}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={AI_BEST_WORST_V80_PREVIEW_DURATION_IN_FRAMES}
        />
        <Composition
          id="BestWorstV8PrimitivePreview16x9"
          component={BestWorstV8PrimitivePreview16x9}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={BEST_WORST_V8_PRIMITIVE_PREVIEW_DURATION_IN_FRAMES}
        />
        <Composition
          id="TrainingCamp16x9-V80-WithSfx"
          component={TrainingCampV80Talk16x9WithSfx}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={TRAINING_CAMP_V80_DURATION_IN_FRAMES}
        />
        <Composition
          id="TrainingCamp16x9-V80-NoSfx"
          component={TrainingCampV80Talk16x9NoSfx}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={TRAINING_CAMP_V80_DURATION_IN_FRAMES}
        />
        <Composition
          id="AICognitivePosition16x9-V80-WithSfx"
          component={AICognitivePositionV80Talk16x9WithSfx}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={AI_COGNITIVE_POSITION_V80_DURATION_IN_FRAMES}
        />
        <Composition
          id="AICognitivePosition16x9-V80-NoSfx"
          component={AICognitivePositionV80Talk16x9NoSfx}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={AI_COGNITIVE_POSITION_V80_DURATION_IN_FRAMES}
        />
        <Composition
          id="AICognitivePosition16x9-V73-WithSfx"
          component={AICognitivePositionV73Talk16x9WithSfx}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={AI_COGNITIVE_POSITION_V73_DURATION_IN_FRAMES}
        />
        <Composition
          id="AICognitivePosition16x9-V73-NoSfx"
          component={AICognitivePositionV73Talk16x9NoSfx}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={AI_COGNITIVE_POSITION_V73_DURATION_IN_FRAMES}
        />
        <Composition
          id="AISelfMedia16x9-V73-WithSfx"
          component={AISelfMediaV73Talk16x9WithSfx}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={AI_SELF_MEDIA_V73_DURATION_IN_FRAMES}
        />
        <Composition
          id="AISelfMedia16x9-V73-NoSfx"
          component={AISelfMediaV73Talk16x9NoSfx}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={AI_SELF_MEDIA_V73_DURATION_IN_FRAMES}
        />
        <Composition
          id="AISelfMediaAssetPreflight16x9-WithSfx"
          component={AISelfMediaAssetPreflight16x9WithSfx}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={AI_SELF_MEDIA_ASSET_PREFLIGHT_DURATION_IN_FRAMES}
        />
        <Composition
          id="AISelfMediaAssetPreflight16x9-NoSfx"
          component={AISelfMediaAssetPreflight16x9NoSfx}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={AI_SELF_MEDIA_ASSET_PREFLIGHT_DURATION_IN_FRAMES}
        />
        <Composition
          id="AIProductivity16x9-V73-WithSfx"
          component={AIProductivityV73Talk16x9WithSfx}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={AI_PRODUCTIVITY_V73_DURATION_IN_FRAMES}
        />
        <Composition
          id="AIProductivity16x9-V73-NoSfx"
          component={AIProductivityV73Talk16x9NoSfx}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={AI_PRODUCTIVITY_V73_DURATION_IN_FRAMES}
        />
        <Composition
          id="Trust16x9-V72-WithSfx"
          component={TrustV72Talk16x9WithSfx}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={TRUST_V72_DURATION_IN_FRAMES}
        />
        <Composition
          id="Trust16x9-V72-NoSfx"
          component={TrustV72Talk16x9NoSfx}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={TRUST_V72_DURATION_IN_FRAMES}
        />
        <Composition
          id="TrustAssetPreflight16x9"
          component={TrustAssetPreflight16x9}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={TRUST_ASSET_PREFLIGHT_DURATION_IN_FRAMES}
        />
        <Composition
          id="TrustStoreScenarioAsset16x9"
          component={TrustStoreScenarioAsset16x9}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={240}
        />
        <Composition
          id="TrustOpcScenarioAsset16x9"
          component={TrustOpcScenarioAsset16x9}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={240}
        />
        <Composition
          id="TrustThreeGatesAsset16x9"
          component={TrustThreeGatesAsset16x9}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={210}
        />
        <Composition
          id="TrustTimelineAsset16x9"
          component={TrustTimelineAsset16x9}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={210}
        />
        <Composition
          id="LanzhouOpc16x9-V72-WithSfx"
          component={LanzhouOpcV72Talk16x9WithSfx}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={LANZHOU_OPC_DURATION_IN_FRAMES}
        />
        <Composition
          id="LanzhouOpc16x9-V72-NoSfx"
          component={LanzhouOpcV72Talk16x9NoSfx}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={LANZHOU_OPC_DURATION_IN_FRAMES}
        />
        <Composition
          id="V72DataDrivenPreview16x9-WithSfx"
          component={V72DataDrivenPreview16x9WithSfx}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={V72_DATA_DRIVEN_PREVIEW_DURATION_IN_FRAMES}
        />
        <Composition
          id="V72DataDrivenPreview16x9-NoSfx"
          component={V72DataDrivenPreview16x9NoSfx}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={V72_DATA_DRIVEN_PREVIEW_DURATION_IN_FRAMES}
        />
        <Composition
          id="CycleAssets16x9-V72-WithSfx"
          component={CycleAssetsV72Talk16x9WithSfx}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={CYCLE_ASSETS_DURATION_IN_FRAMES}
        />
        <Composition
          id="CycleAssets16x9-V72-NoSfx"
          component={CycleAssetsV72Talk16x9NoSfx}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={CYCLE_ASSETS_DURATION_IN_FRAMES}
        />
        <Composition
          id="ChildAIInterview16x9-V72-WithSfx"
          component={ChildAIInterviewV72WithSfx}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={CHILD_AI_INTERVIEW_DURATION_IN_FRAMES}
        />
        <Composition
          id="ChildAIInterview16x9-V72-NoSfx"
          component={ChildAIInterviewV72NoSfx}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={CHILD_AI_INTERVIEW_DURATION_IN_FRAMES}
        />
        <Composition
          id="HokkaidoThreeProjectsTalk16x9-NoSfx"
          component={HokkaidoThreeProjectsTalk16x9}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={HOKKAIDO_THREE_PROJECTS_DURATION_IN_FRAMES}
        />
        <Composition
          id="HokkaidoThreeProjectsTalk16x9-WithSfx"
          component={HokkaidoThreeProjectsTalk16x9WithSfx}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={HOKKAIDO_THREE_PROJECTS_DURATION_IN_FRAMES}
        />
        <Composition
          id="HokkaidoThreeProjectsTalk16x9-V72-NoSfx"
          component={HokkaidoThreeProjectsTalk16x9V72NoSfx}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={HOKKAIDO_THREE_PROJECTS_DURATION_IN_FRAMES}
        />
        <Composition
          id="HokkaidoThreeProjectsTalk16x9-V72-WithSfx"
          component={HokkaidoThreeProjectsTalk16x9V72WithSfx}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={HOKKAIDO_THREE_PROJECTS_DURATION_IN_FRAMES}
        />
        <Composition
          id="HokkaidoThreeProjectsAssetPreflight16x9"
          component={HokkaidoThreeProjectsAssetPreflight16x9}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={HOKKAIDO_THREE_PROJECTS_PREFLIGHT_DURATION_IN_FRAMES}
        />
        <Composition
          id="HokkaidoV71StylePreview16x9-WithSfx"
          component={HokkaidoV71StylePreview16x9}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={HOKKAIDO_V71_PREVIEW_DURATION_IN_FRAMES}
        />
        <Composition
          id="HokkaidoV71StylePreview16x9-NoSfx"
          component={HokkaidoV71StylePreview16x9NoSfx}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={HOKKAIDO_V71_PREVIEW_DURATION_IN_FRAMES}
        />
        <Composition
          id="TwoLedgersV7Talk16x9-WithSfx"
          component={TwoLedgersV7Talk16x9}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={TWO_LEDGER_DURATION_IN_FRAMES}
        />
        <Composition
          id="TwoLedgersV7Talk16x9-NoSfx"
          component={TwoLedgersV7Talk16x9NoSfx}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={TWO_LEDGER_DURATION_IN_FRAMES}
        />
        <Composition
          id="DazhiFormalV7Talk16x9"
          component={DazhiFormalV7Talk16x9}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={DAZHI_FORMAL_DURATION_IN_FRAMES}
        />
        <Composition
          id="WAICV7TransparentTest16x9"
          component={WAICV7TransparentTest16x9}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={WAIC_V7_TEST_DURATION_IN_FRAMES}
        />
        <Composition
          id="WAICV6Talk16x9-Final"
          component={WAICV6Talk16x9}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={WAIC_V6_DURATION_IN_FRAMES}
        />
        <Composition
          id="WAICV6Talk16x9-Preview"
          component={WAICV6Preview16x9}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={WAIC_V6_PREVIEW_DURATION_IN_FRAMES}
        />
        <Composition
          id="RuishengGeoField16x9-V2"
          component={RuishengGeoField16x9V2}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={RUISHENG_GEO_V2_DURATION_IN_FRAMES}
        />
        <Composition
          id="RuishengGeoField16x9-Final"
          component={RuishengGeoField16x9}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={RUISHENG_GEO_DURATION_IN_FRAMES}
        />
        <Composition
          id="AILandingFieldDocumentaryV2-Rough"
          component={AILandingFieldDocumentaryV2}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={AI_LANDING_DOCUMENTARY_V2_DURATION_IN_FRAMES}
        />
        <Composition
          id="AILandingFieldTalk16x9-Final"
          component={AILandingFieldTalk16x9}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={AI_LANDING_DURATION_IN_FRAMES}
        />
        <Composition
          id="TokenV5Talk16x9-Final"
          component={TokenV5Talk16x9}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={6595}
        />
        <Composition
          id="TokenV5AssetPreview16x9"
          component={TokenV5AssetPreview16x9}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={1680}
        />
        <Composition
          id="Digital1Talk16x9-Final"
          component={DigitalOneTalk16x9}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={5247}
        />
        <Composition
          id="AIStoreTalk16x9-Final"
          component={AIStoreTalk16x9}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={7462}
        />
        <Composition
          id="AIStoreAssetPreview16x9"
          component={AIStoreAssetPreview16x9}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={960}
        />
        <Composition
          id="AIBizTalk16x9"
          component={AIBizTalk16x9}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={2380}
          defaultProps={defaultTalkProps}
        />
        <Composition
          id="AIBizTalk16x9-IMG1926"
          component={AIBizTalk16x9}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={1848}
          defaultProps={localBossAiProps}
        />
        <Composition
          id="AIBizTalk16x9-IMG1926-v2"
          component={AIBizTalk16x9}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={1848}
          defaultProps={localBossAiV2Props}
        />
        <Composition
          id="AIBizTalk16x9-OCRDemo"
          component={AIBizTalk16x9}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={120}
          defaultProps={localBossAiOcrDemoProps}
        />
        <Composition
          id="AIBizTalk16x9-SmallBusinessAI-v1"
          component={AIBizTalk16x9}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={5082}
          defaultProps={smallBusinessAiV1Props}
        />
        <Composition
          id="AIBizTalk16x9-GansuStoreAI-Talk01"
          component={AIBizTalk16x9}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={3543}
          defaultProps={gansuStoreAiTalk01Props}
        />
        <Composition
          id="AIBizTalk16x9-GEO-AIRecommend-Talk01"
          component={AIBizTalk16x9}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={7306}
          defaultProps={geoAiRecommendTalk01Props}
        />
        <Composition
          id="AIBizTalk16x9-LocalBusinessAI-Daily-Talk01"
          component={AIBizTalk16x9}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={4405}
          defaultProps={localBusinessAiDailyTalk01Props}
        />
        <Composition
          id="AIBizTalk16x9-OPC-WestYouth-Talk01"
          component={AIBizTalk16x9}
          width={1920}
          height={1080}
          fps={30}
          durationInFrames={5670}
          defaultProps={opcWestYouthTalk01Props}
        />
        <Still
          id="CoverStill"
          component={CoverStill}
          width={1920}
          height={1080}
          defaultProps={defaultTalkProps}
        />
        <Still
          id="CoverStill3x4"
          component={CoverStill3x4}
          width={1080}
          height={1440}
          defaultProps={defaultTalkProps}
        />
        <Still
          id="CoverStill3x4-IMG1926"
          component={CoverStill3x4}
          width={1080}
          height={1440}
          defaultProps={localBossAiProps}
        />
        <Still
          id="CoverStill3x4-IMG1926-v2"
          component={CoverStill3x4}
          width={1080}
          height={1440}
          defaultProps={localBossAiV2Props}
        />
        <Still
          id="CoverStill9x16"
          component={CoverStill9x16}
          width={1080}
          height={1920}
          defaultProps={defaultTalkProps}
        />
      </Folder>
    </>
  );
};
